# Clippy configuration

# Deny certain lints in CI
warn-on-all-wildcard-imports = true

# Allow certain patterns
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true

# Enforce documentation
missing-docs-in-crate-items = true
